title: Harshal Pandit
logo: /assets/img/Latest_Passport_Size.jpg

description: 
<p align = "center">
<a href = "docs/harshalpandit_resume.pdf">Resume</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
