title: Harshal Pandit
logo: /assets/img/Latest_Passport_Size.jpg

description: 
<p align = "center">
<a href = "docs/harshalpandit_resume.pdf">Resume</a>
<a href = "https://www.linkedin.com/in/harshalpandit13">LinkedIn</a>
<a href = "https://www.github.com/Harshal1308">GitHub</a>

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
